### ISSUE TITLE
error from ocsp agent

### ISSUE THREAD

**Issue by devsnek** [indutny/ocsp#32]
/home/noms/spoop2/server/node_modules/ocsp/lib/ocsp/agent.js:70
  var cert = socket.ssl.getPeerCertificate(true);
                        ^

TypeError: Cannot read property 'getPeerCertificate' of null
    at Agent.handleOCSPResponse (/home/noms/spoop2/server/node_modules/ocsp/lib/ocsp/agent.js:70:25)
    at TLSSocket.<anonymous> (/home/noms/spoop2/server/node_modules/ocsp/lib/ocsp/agent.js:52:17)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)

**Comment by KSR-Yasuda** [comment]
It looks working with the fix below, on Node.js v12.16.1:

```diff
--- a/lib/ocsp/agent.js
+++ b/lib/ocsp/agent.js
@@ -67,10 +67,10 @@ Agent.prototype.createConnection = funct
 Agent.prototype.handleOCSPResponse = function handleOCSPResponse(socket,
                                                                  stapling,
                                                                  cb) {
-  var cert = socket.ssl.getPeerCertificate(true);
-  var issuer = cert.issuerCertificate;
+  var cert = (socket.ssl || socket).getPeerCertificate(true);
+  var issuer = cert && cert.issuerCertificate;
 
-  cert = cert.raw;
+  cert = cert && cert.raw;
   try {
     cert = rfc5280.Certificate.decode(cert, 'der');
 
```

In the API document, [`tlsSocket.getPeerCertificate()`](https://nodejs.org/docs/latest-v12.x/api/tls.html#tls_tlssocket_getpeercertificate_detailed) exists,
but not `tlsSocket.ssl` or its `getPeerCertificate()`.

Other lines were also referring `null` object.

Something's wrong, perhaps with `dependencies` modules update, or such.
