### ISSUE TITLE
OCSP Cache timeout error

### ISSUE THREAD

**Issue by JoneXie1986** [indutny/ocsp#4]
Thank you for this node module.

catch a exception, when the cache's timeout been trigged，

```javascript
Worker 144574 catch uncaughtException!!!
[TypeError: Cannot convert undefined or null to object]
TypeError: Cannot convert undefined or null to object
    at null._onTimeout (/data/system/ws_cluster/node_modules/ocsp/lib/ocsp/cache.js:36:25)
    at Timer.listOnTimeout (timers.js:92:15)
```

I found this code:
```javascript
Cache.prototype.store = function store(id, response, maxTime, callback) {
  if (this.cache.hasOwnProperty(id))
    clearTimeout(this.cache[id].timer);
  this.cache[id] = {
    response: response,
    timer: setTimeout(function() {
      delete this.cache[id];
    }, maxTime)
  };

  callback(null, null);
};

```
I think, the scope of ```this.cache[id]``` is error?

fix this it, 
```javascript
Cache.prototype.store = function store(id, response, maxTime, callback) {
  if (this.cache.hasOwnProperty(id))
    clearTimeout(this.cache[id].timer);

  var self = this;
  this.cache[id] = {
    response: response,
    timer: setTimeout(function() {
      delete self.cache[id];
    }, maxTime)
  };

  callback(null, null);
};

```

Is it OK?

**Comment by indutny** [comment]
Fix has been landed!
