### ISSUE TITLE
Getting error in NODE_ENV=production

### ISSUE THREAD

**Issue by Rush** [indutny/ocsp#6]
edit: Just found out that the following errors I get when running ssl without forking ... gonna investigate more. Possibly it is not related to ocsp package at all.

-----------

`OCSPRequest` is getting `cert` and `issuer` as `null`:
```
server.on('OCSPRequest', function(cert, issuer, cb) {
```
```
node_modules/ocsp/lib/ocsp/utils.js:107
var der = raw.toString().match(new RegExp(

TypeError: Cannot read property 'toString' of null
at Object.toDER (/opt/project/src/node_modules/ocsp/lib/ocsp/utils.js:107:16)
at Object.getOCSPURI (/opt/project/src/node_modules/ocsp/lib/ocsp/api.js:10:25)
at Server.<anonymous> (/opt/project/src/node_modules/http-master/src/HttpMasterWor...239:12)
at emitThree (events.js:97:13)
at Server.emit (events.js:175:7)
at requestOCSP (_tls_wrap.js:121:17)
at _tls_wrap.js:165:5
at _tls_wrap.js:104:5
at TLSSocket.sniCallback [as _SNICallback] (/opt/virtkick/src/node_modules/http-mas...:68:22)
at loadSNI (_tls_wrap.js:89:8)
```

Other error I am getting (linked t othe first one is)
```
 _tls_wrap.js:172
 self._handle.certCbDone();
 ^
 Error: error:140C6043:SSL routines:SSL_use_certificate:passed a null parameter
 at Error (native)
 at _tls_wrap.js:172:20
 at requestOCSP (_tls_wrap.js:111:12)
 at _tls_wrap.js:165:5
 at _tls_wrap.js:104:5
 at TLSSocket.sniCallback [as _SNICallback] (/opt/project/src/node_modules/http-mas...:68:22)
 at loadSNI (_tls_wrap.js:89:8)
 at TLSSocket.oncertcb (_tls_wrap.js:162:3)
 at _tls_wrap.js:153:18
 at loadSession (_tls_wrap.js:79:5)
```

Node version is `4.2.2` and latest `ocsp`.

**Comment by Rush** [comment]
I haven't identified the issue but it's not ocsp's fault, sorry.
